// Generated by claude

import { it, describe, beforeEach, afterEach, expect, vi } from 'vitest';
import {
    getClosestStation,
    getStopsForParentStation,
    getDeparturesForStop,
} from './stop-utils.js';

// Mock the gtfs module
vi.mock('gtfs', () => ({
    getStops: vi.fn(),
    getStoptimes: vi.fn(),
}));

import { getStops, getStoptimes } from 'gtfs';

describe('stop-utils', () => {
    beforeEach(() => {
        vi.clearAllMocks();
    });

    describe('getClosestStation', () => {
        it('returns the first station from nearby search', async () => {
            const mockStation = {
                stop_id: 'Q7005',
                stop_name: 'Clareview Station',
                stop_lat: 53.601592,
                stop_lon: -113.411819,
                location_type: 1 as const,
            };

            vi.mocked(getStops).mockResolvedValue([mockStation]);

            const result = await getClosestStation({
                lat: 53.601592,
                lon: -113.411819,
            });

            expect(result).toEqual(mockStation);
            expect(getStops).toHaveBeenCalledWith(
                {
                    location_type: 1,
                    stop_lat: 53.601592,
                    stop_lon: -113.411819,
                },
                [],
                [],
                { bounding_box_side_m: 999999999 }
            );
        });

        it('handles empty coordinates gracefully', async () => {
            const mockStation = { stop_id: 'TEST', stop_name: 'Test Station' };
            vi.mocked(getStops).mockResolvedValue([mockStation]);

            const result = await getClosestStation({});

            expect(result).toEqual(mockStation);
            expect(getStops).toHaveBeenCalledWith(
                {
                    location_type: 1,
                    stop_lat: undefined,
                    stop_lon: undefined,
                },
                [],
                [],
                { bounding_box_side_m: 999999999 }
            );
        });
    });

    describe('getStopsForParentStation', () => {
        it('returns platforms for a parent station', () => {
            const mockPlatforms = [
                {
                    stop_id: '49821',
                    parent_station: 'Q7018',
                    stop_name: 'Century Park Station',
                },
                {
                    stop_id: '49822',
                    parent_station: 'Q7018',
                    stop_name: 'Century Park Station',
                },
            ];

            vi.mocked(getStops).mockReturnValue(mockPlatforms);

            const result = getStopsForParentStation('Q7018');

            expect(result).toEqual(mockPlatforms);
            expect(getStops).toHaveBeenCalledWith({
                parent_station: 'Q7018',
            });
        });

        it('returns empty array when no platforms found', () => {
            vi.mocked(getStops).mockReturnValue([]);

            const result = getStopsForParentStation('INVALID');

            expect(result).toEqual([]);
        });
    });

    describe('getDeparturesForStop', () => {
        beforeEach(() => {
            vi.useFakeTimers();
            vi.setSystemTime(new Date(2025, 8, 19, 15, 30, 0)); // Sept 19, 2025, 3:30 PM
        });

        afterEach(() => {
            vi.useRealTimers();
        });

        it('returns filtered departures excluding terminating trips', async () => {
            const mockStopInfo = {
                stop_id: '49822',
                parent_station: 'Q7018',
                stop_name: 'Century Park Station',
            };

            const mockParentStation = {
                stop_id: 'Q7018',
                stop_name: 'Century Park Station',
            };

            const mockStoptimes = [
                {
                    stop_id: '49822',
                    trip_id: 'trip1',
                    stop_headsign: 'Century Park', // Should be filtered out
                    departure_time: '15:45:00',
                    departure_timestamp: 56700,
                    stop_sequence: 1,
                },
                {
                    stop_id: '49822',
                    trip_id: 'trip2',
                    stop_headsign: 'Clareview', // Should be kept
                    departure_time: '16:00:00',
                    departure_timestamp: 57600,
                    stop_sequence: 2,
                },
            ];

            // Mock getStops calls for stop info and parent station
            vi.mocked(getStops)
                .mockReturnValueOnce([mockStopInfo]) // First call for stop info
                .mockReturnValueOnce([mockParentStation]); // Second call for parent station

            vi.mocked(getStoptimes).mockReturnValue(mockStoptimes);

            const result = await getDeparturesForStop({ stopId: '49822' });

            expect(result).toHaveLength(1);
            expect(result[0].stop_headsign).toBe('Clareview');
            expect(result[0].trip_id).toBe('trip2');
        });

        it('keeps all departures when none match station name', async () => {
            const mockStopInfo = {
                stop_id: '79772',
                parent_station: 'Q7005',
                stop_name: 'Clareview Station',
            };

            const mockParentStation = {
                stop_id: 'Q7005',
                stop_name: 'Clareview Station',
            };

            const mockStoptimes = [
                {
                    stop_id: '79772',
                    trip_id: 'trip1',
                    stop_headsign: 'Century Park',
                    departure_time: '15:45:00',
                    stop_sequence: 1,
                },
                {
                    stop_id: '79772',
                    trip_id: 'trip2',
                    stop_headsign: 'Downtown',
                    departure_time: '16:00:00',
                    stop_sequence: 2,
                },
            ];

            vi.mocked(getStops)
                .mockReturnValueOnce([mockStopInfo])
                .mockReturnValueOnce([mockParentStation]);

            vi.mocked(getStoptimes).mockReturnValue(mockStoptimes);

            const result = await getDeparturesForStop({ stopId: '79772' });

            expect(result).toHaveLength(2);
            expect(result.map((d) => d.stop_headsign)).toEqual([
                'Century Park',
                'Downtown',
            ]);
        });

        it('handles null headsigns gracefully', async () => {
            const mockStopInfo = {
                stop_id: '12345',
                parent_station: 'Q1234',
                stop_name: 'Test Station',
            };

            const mockParentStation = {
                stop_id: 'Q1234',
                stop_name: 'Test Station',
            };

            const mockStoptimes = [
                {
                    stop_id: '12345',
                    trip_id: 'trip1',
                    stop_headsign: undefined,
                    departure_time: '15:45:00',
                    stop_sequence: 1,
                },
            ];

            vi.mocked(getStops)
                .mockReturnValueOnce([mockStopInfo])
                .mockReturnValueOnce([mockParentStation]);

            vi.mocked(getStoptimes).mockReturnValue(mockStoptimes);

            const result = await getDeparturesForStop({ stopId: '12345' });

            expect(result).toHaveLength(1);
            expect(result[0].stop_headsign).toBeUndefined();
        });

        it('respects the limit parameter', async () => {
            const mockStopInfo = {
                stop_id: '12345',
                parent_station: 'Q1234',
                stop_name: 'Test Station',
            };

            const mockParentStation = {
                stop_id: 'Q1234',
                stop_name: 'Test Station',
            };

            const mockStoptimes = Array.from({ length: 10 }, (_, i) => ({
                stop_id: '12345',
                trip_id: `trip${i}`,
                stop_headsign: 'Destination',
                departure_time: `${16 + Math.floor(i / 4)}:${(i % 4) * 15}:00`,
                stop_sequence: i + 1,
            }));

            vi.mocked(getStops)
                .mockReturnValueOnce([mockStopInfo])
                .mockReturnValueOnce([mockParentStation]);

            vi.mocked(getStoptimes).mockReturnValue(mockStoptimes);

            const result = await getDeparturesForStop({
                stopId: '12345',
                limit: 3,
            });

            expect(result).toHaveLength(3);
        });

        it('sorts departures by timestamp when available', async () => {
            const mockStopInfo = {
                stop_id: '12345',
                parent_station: 'Q1234',
                stop_name: 'Test Station',
            };

            const mockParentStation = {
                stop_id: 'Q1234',
                stop_name: 'Test Station',
            };

            const mockStoptimes = [
                {
                    stop_id: '12345',
                    trip_id: 'trip2',
                    stop_headsign: 'Second',
                    departure_time: '16:00:00',
                    departure_timestamp: 57600,
                    stop_sequence: 2,
                },
                {
                    stop_id: '12345',
                    trip_id: 'trip1',
                    stop_headsign: 'First',
                    departure_time: '15:45:00',
                    departure_timestamp: 56700,
                    stop_sequence: 1,
                },
            ];

            vi.mocked(getStops)
                .mockReturnValueOnce([mockStopInfo])
                .mockReturnValueOnce([mockParentStation]);

            vi.mocked(getStoptimes).mockReturnValue(mockStoptimes);

            const result = await getDeparturesForStop({ stopId: '12345' });

            expect(result).toHaveLength(2);
            expect(result[0].stop_headsign).toBe('First');
            expect(result[1].stop_headsign).toBe('Second');
        });

        it('throws error when stopId is empty', async () => {
            await expect(getDeparturesForStop({ stopId: '' })).rejects.toThrow(
                'getDeparturesForStop: stopId is required'
            );
        });

        it('handles missing parent station gracefully', async () => {
            const mockStopInfo = {
                stop_id: '12345',
                parent_station: undefined,
                stop_name: 'Test Station',
            };

            const mockStoptimes = [
                {
                    stop_id: '12345',
                    trip_id: 'trip1',
                    stop_headsign: 'Destination',
                    departure_time: '15:45:00',
                    stop_sequence: 1,
                },
            ];

            vi.mocked(getStops).mockReturnValueOnce([mockStopInfo]);
            vi.mocked(getStoptimes).mockReturnValue(mockStoptimes);

            const result = await getDeparturesForStop({ stopId: '12345' });

            expect(result).toHaveLength(1);
            expect(result[0].stop_headsign).toBe('Destination');
        });
    });
});
